### ISSUE TITLE
HydX: gegevens van UitlaatPunt

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#100]
Een uitlaat komt in de hydx zowel voor bij de knooppunten als bij de kunstwerken (KNP_TYP en KWK_TYP). Uitlaatpunten R12430 en R12414 staan de in de ttl als een uitlaatpunt. In de hydx komen deze terug in de csv knooppunt als een knoop met PUT_IDE “UitlaatPunt” (in plaats van het rdfs: label) en het veld KNP_TYP is leeg (in plaats van “UIT”).

Verder worden bij beide uitlaatpunten in de csv knooppunt de velden KNP_BRE en KNP_LEN gevuld met waarde 1 (zonder dat dit in de ttl aanwezig was), het veld KNP_VRM gevuld met waarde RHK en het veld MVD_SCH gevuld met KNV (wat beide ook niet in de ttl aanwezig is). In het bestand kunstwerk csv komen beide uitlaatpunten terug als UIT (KWK_TYP).

[Riel_hoofdriolering_2023-11-24 copy.txt](https://github.com/StichtingRIONED/GWSW_Apps/files/14920332/Riel_hoofdriolering_2023-11-24.copy.txt)

**Comment by MarinusVonhof** [comment]
Via een ander issue het label van Uitlaatpunt al toegevoegd. Voor het omgaan met punten en hulpstukken, zie https://stichtingrioned.github.io/gwsw-hyd/#gegevens-hulpstukken
