### ISSUE TITLE
HydX: Uitlaatconstructie als Inspectieput?

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#101]
Uitlaatconstructie R04135 is in ttl opgenomen als een uitlaatconstructie met een aspect Uitlaatpunt. In hydx komt dit terug als een inspectieput.

Uitlaatconstructies met als aspect een instantie van Uitlaatpunt komen als inspectieputten mee in hydx export. Dat zouden uitlaten moeten zijn.

Uitlaatpunten als instanties met coordinaten (dat zijn dus andere uitlaatpunten dan hierboven benoemd, want die hebben geen coordinaten) worden in knooppunt.csv weggezet. Veld KNP_TYP is dan echter leeg, terwijl ik UIT verwacht. In kunstwerk.csv staan diezelfde uitlaatpunten ook opgenomen. Veld KWK_TYP is dan gevuld met UIT. Staan deze punten dan dubbel geregistreerd? Het is wat onduidelijk hier.

[Riel_hoofdriolering_2023-11-24 copy.txt](https://github.com/StichtingRIONED/GWSW_Apps/files/14920337/Riel_hoofdriolering_2023-11-24.copy.txt)

**Comment by MarinusVonhof** [comment]
Niet aangepast, staat dit goed in de dataset? Zie de modelleerprincipes in https://apps.gwsw.nl/doc/GWSW.orox%20Opbouw%20dataset.pdf .
Is zo gemodelleerd in het didactisch stelsel https://apps.gwsw.nl/doc/GwswDataset__DidacStelsel_v1.6.orox.ttl . Daarop getest, die draait goed.

**Comment by woutervriel** [comment]
Ook met het didactisch stelsel klopt het niet. Uitlaatconstructie met label '01009U' heeft een aspect van het type UitlaatPunt ('01009U/U'). Echter, de knoop '01009U/U' in knooppunt.csv heeft dan geen type in veld KNP_TYP. Je zou hier dan UIT verwachten.

Ik zie overigens dat de leiding in het didactisch stelsel rechtstreeks aansluit op het UitlaatPunt, terwijl in onze dataset de leiding aansluit op de Uitlaatconstructie. In https://apps.gwsw.nl/doc/GWSW.orox%20Opbouw%20dataset.pdf staat dat dat wel zo moet. Dat zal ik dan aanpassen sowieso.

**Comment by MarinusVonhof** [comment]
De query knooppunt.rq aangepast: ook type uitlaat meenemen. Nu wordt ook KNP_TYP "UIT" gevuld.

Overleg gehad over netwerk met UitlaatPunt. Het begin/eindpunt leiding kan aansluiten op UitlaatPunt met of zonder Uitlaatconstructie. Zo nodig kan binnen de Uitlaatconstructie bijvoorbeeld nog een klep worden gedefinieerd. Dan sluit het begin/eindpunt leiding aan op de bouwwerkorientatie die via de Doorlaat aansluit op het UitlaatPunt.
