### ISSUE TITLE
HydX: Hoogte van een compartiment

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#102]
Compartimenten hebben geen KNP_BOK en MVD_NIV. In GWSW-datamodel moet kenmerk hoogte compartiment worden toegevoegd. Volgens de query hyd_knooppunt wordt aan een compartiment een maaiveldhoogte toegekend (MVD_NIV), ontleend aan de hoofdconstructie (deze dus in beheerapplicatie registreren en in ttl meegeven). Vervolgens kan dan net zoals bij de inspectieputten de KNP_BOK worden bepaald.

**Comment by MarinusVonhof** [comment]
Volgens mij werkt dit al goed, getest op het didactisch stelsel, zie put 09001 in https://apps.gwsw.nl/doc/GwswDataset__DidacStelsel_v1.6.orox.ttl .
Wel het nieuwe concept HoogteCompartiment in de query toegevoegd, deze waarde wordt optioneel gebruikt.
