### ISSUE TITLE
HydX: verwijdering Blinde en Verdekte putten

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#103]
Blinde en verdekte putten gaan niet mee naar hydx. Deze worden verwijderd. De aansluitende leidingen gaan wel mee naar hydx (als type leiding tenminste in de query voorkomt). Deze leiding mist vervolgens een begin- of eindknoop. Dit wordt vervolgens in de csv van de knopen (KN1_IDE of KN2_IDE) onbekend. Blinde en verdekte putten maken gewoon onderdeel uit van een netwerk. Blinde put heeft geen opening aan de bovenzijde en bij een verdekte put is enkel de bovenzijde niet zichtbaar. Maar beide knopen zijn wel aanwezig en moeten dus meegenomen worden als inspectieput met maaiveldschematisering gekneveld.

**Comment by MarinusVonhof** [comment]
Niet aangepast. De typeringen BlindePut en VerdektePut zijn in de dataset altijd extra typeringen. Het functionele type (Inspectieput, Overstortput, ...) is daarnaast altijd nodig. De blinde put wordt wel meegenomen in de queries (wordt "Gekneveld"), zie ook https://github.com/StichtingRIONED/gwsw_queries/blob/main/apps/Hyd/Hyd_Knooppunt.rq . "Gekneveld" wordt niet gehanteerd voor verdekte putten omdat de mate van verdekking onbekend is.
