### ISSUE TITLE
HydX: verwijdering hulpstukken

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#106]
Bij conversie naar hydx worden hulpstukken (verbindingsstukken zoals bochtstuk en verloopstuk) verwijderd. Verbingsstukken tussen twee vrijvervalleidingen moeten gewoon meekomen in de HydX export.

**Comment by MarinusVonhof** [comment]
Niet kunnen reproduceren, getest met knooppunt "04010" in didactisch stelsel. 04010 is van type gwsw:Verbindingsstuk. Zou goed moeten werken, zie ook de query Hyd_Knooppunt.rq. Denk er wel aan dat een hulpstuk niet bestaat in HydX, dat wordt een geknevelde inspectieput met minimale afmetingen (zie ook https://stichtingrioned.github.io/gwsw-hyd#gegevens-hulpstukken)
