### ISSUE TITLE
HydX: kopieren van gegevens van hoofdconstructie naar compartimenten

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#108]
Voorbeeld: er is een stuwput met twee compartimenten. De stuwput heeft een maaiveldschematisering Reservoir, en een BergendOppervlak van 100 m2.

In knooppunt.csv wordt die maaiveldschematisering en de 100 m2 bergendoppervlak gekopieerd naar de twee compartimenten die onderdeel zijn van de stuwput. Kortom,  waar we eerder 100 m2 bergendoppervlak hadden, is dat nu 200 m2 geworden.

**Comment by MarinusVonhof** [comment]
Bedankt voor de tip, is gecorrigeerd.
Bergend oppervlak is het enige gegeven dat binnenkomt vanaf het compositie-object en verdeeld moet worden.
