### ISSUE TITLE
HydX: geen weergave rdfs:label van verbindingen, anders dan leidingen

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#109]
Verbindingen, anders dan leidingen, zoals overstortdrempels of pompen of doorlaten, krijgen geen rdfs:label mee in veld LEI_IDE in Verbinding.csv.

Nu moet je een verbindingen handmatig zoeken via de kop* nummers in Knooppunt.csv en dat is erg onhandig.

**Comment by MarinusVonhof** [comment]
Bedankt voor de tip, aangevuld.
Als er een rdfs:label in de dataset staat wordt ie vermeld in LEI_IDE
