### ISSUE TITLE
HydX: incorrecte registratie overstortdrempel met UitlaatPunt als Eindpuntonderdeel

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#110]
Een Overstortdrempel, waarbij de het beginpunt een compartiment is en het eindpunt een uitlaatpunt komt incorrect terecht in Verbinding.csv.

Ten eerste wordt het betreffende uitlaatpunt niet met zijn eigen rdfs:label opgenomen in de lijst bij PUT_IDE in Knooppunt.csv. Ten tweede staat in Verbinding.csv in veld KN2_IDE de string 'onbekend', terwijl deze IDE weldegelijk bekend is in de ttl.

**Comment by MarinusVonhof** [comment]
Bedankt voor de tip, gecorrigeerd.
Queries Hyd_Drempel, Hyd_Knooppunt aangepast. 
Om het strak te houden (en de queries draaiende te houden) is een rdf:label bij een gwsw:Aansluiting verplicht (was al opgenomen in het OroX-document).
