### ISSUE TITLE
Multi-geometrieën accepteren en verwerken in GWSW Datasets

### ISSUE THREAD

**Issue by sweco-nlmarv** [StichtingRIONED/GWSW_Apps#57]
Eerste aanpassing van GWSW-Geo gedaan: MultiPoint, MultiLinestring, MultiPolygon, MultiCurve en MultiSurface wordt nu ook verwerkt.
Document GWSW-OroX hier nog wel op aanpassen.

**Comment by StichtingRIONED** [comment]
GWSW-OroX document erop aangepast. Issue afgerond
