### ISSUE TITLE
GWSW Geo - Geo-thema's: in queries volledige URI opnemen

### ISSUE THREAD

**Issue by StichtingRIONED** [StichtingRIONED/GWSW_Apps#59]
In de gebruikte queries altijd de volledige URI opnemen, dus de prefix uitschrijven. Voorsorteren op landelijke URI-strategie, wordt belangrijker (ook voor GWSW Kentallen)

**Comment by MarinusVonhof** [comment]
Zie ook issue 62

**Comment by MarinusVonhof** [comment]
Gelijk met issue 62 gesloten: De complete uri's komen nu mee in geo-thema Default (opgeleverd dd 20230416)
