### ISSUE TITLE
GWSW Geo: Uitlaatpunt ontbreekt in query default_punt (Wouter van Riel)

### ISSUE THREAD

**Issue by StichtingRIONED** [StichtingRIONED/GWSW_Apps#61]
Uitlaatpunt (aansluitpunt) is zelf van het type TopologischElement (een super-super-type van oriëntatie) en hoeft niet altijd deel te zijn van een constructie. Om die reden komen ze niet mee.

**Comment by MarinusVonhof** [comment]
Opgelost, zie issue elders (ook closed op 20230426)
