### ISSUE TITLE
GWSW Geo - weergave volledige uri

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#62]
**Geo-app:** 
In de teruglevering wordt in de volgende lagen de volledige uri (namespace + guid) niet getoond:
- Default: Lijn
- Default: Punt
- Default: Punt_deel
- Default: Buitengrens

Bij 'Lijn_deel' komt dat wel goed mee.

**Comment by MarinusVonhof** [comment]
Zie ook issue 59

**Comment by StichtingRIONED** [comment]
20220921/mv: wees consequent, overal doorvoeren
20220224/wvr: voorleggen aan C. Helmons (voorzitter Geo groep)

**Comment by MarinusVonhof** [comment]
De complete uri's komen nu mee in geo-thema Default (opgeleverd dd 20230416)
