### ISSUE TITLE
GWSW Geo - WFS service werkt niet goed in Arcgis Pro

### ISSUE THREAD

**Issue by MarcvanderWulp** [StichtingRIONED/GWSW_Apps#66]
Wanneer in Pro de WFS ingeladen wordt wordt een correcte request gestuurd richting gwsw.nl, en deze krijgt met code 200 een application/xml terug. Het lijkt er echter op dat Pro moeite heeft met het geleverde format van deze XML.

Kan er onderzocht worden of dit verbeterd kan worden?

**Comment by MarinusVonhof** [comment]
GeoServer als paralelle service geïnstalleerd. Dat lost het op?

**Comment by MarinusVonhof** [comment]
Het verwerken van (3D?) coördinaten in ArcGIS loopt niet lekker. Dat wordt verholpen door een recentere versie dan WFS 1.0.0 te gebruiken (bijv. 2.0.0.).
