### ISSUE TITLE
GWSW Hyd - Afsluitstuk wordt inspectieput in HydX

### ISSUE THREAD

**Issue by StichtingRIONED** [StichtingRIONED/GWSW_Apps#69]
20220921/mv: zoek het uit, in queries, in app?
20220812/mv: Mogelijk een issue voor GWSW-Apps

**Comment by woutervriel** [comment]
Deze opheffen

**Comment by MarinusVonhof** [comment]
Hulpstukken in het algemeen komen mee (ook de Punt-geometrie). Alle onbekende puttypes die ook van type Knooppunt worden "Inpectieput".
