### ISSUE TITLE
GWSW HydX - Nooduitlaat en UitlaatPunt niet in hydx export

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#71]
Type Nooduitlaat en UitlaatPunt gaan niet als een uitlaat (UIT, outfall) naar de hydx export. 
Type Uitlaatconstructie gaat wel naar HydX als KNP_TYP - UIT.

**Comment by woutervriel** [comment]
Wouter en Marco checken ook .ttl Heusden. Wouter stuurt Marinus .ttl van Laren

**Comment by MarinusVonhof** [comment]
Issue was reproduceerbaar in TestHyd. Nooduitlaat en Uitlaatpunt als zelfstandige uitlaat toegevoegd. 
De dataset GwswDataset__DidacStelsel_v1.6.orox.ttl aangepast met deze test-types
De queries Knooppunt.rq en Uitlaat.rq aangepast
De app aangepast
Het document GWSW.orox aangepast, toelichting op gebruik UitlaatPunt
