### ISSUE TITLE
GWSW HydX - Verbindingsstuk wordt Inspectieput

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#72]
Type Verbindingsstuk wordt Inspectieput in hydx export. Dit zijn in datasets van gemeenten vaak “tussenpunten” in drukleidingen, maar drukleidingen gaan niet mee naar hydx. Deze verbindingsstukken worden daarmee losse inspectieputten zonder verbinding met leidingen, omdat het tracé van een persleiding/drukleiding kan niet worden meegegeven in hydx.

**Comment by woutervriel** [comment]
Marinus zoekt het uit

**Comment by MarinusVonhof** [comment]
Test dataset uitgebreid met persleiding-verbinding, queries en app aangepast

- Geo-query Netwerk_Knooppunt.rq aangepast
- Dataset TestHyd (didactische stelsel aangepast), verbindingsstuk tussen persleidingen erbij
- App aangepast: knooppunten achteraf wegschrijven, alleen als ze voorkomen in verbinding.csv
