### ISSUE TITLE
GWSW HydX - Veld KNP_BOK wordt niet gevuld

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#73]
Veld KNP_BOK (niveau binnenonderkant put, in m t.o.v. NAP) wordt niet ingevuld in HydX export, ondanks dat de gegevens daarvoor wel aanwezig zijn in de .ttl (maaiveldhoogte en hoogte put).

**Comment by woutervriel** [comment]
Duidelijk. Marinus zoekt het uit

**Comment by MarinusVonhof** [comment]
Veld KNP_BOK wordt in eerste instantie afgelezen uit punt-object (de z-waarde). Als die ontbreekt wordt nu het veld afgeleid van maaiveld en puthoogte
- Query hyd_knooppunt.rq aangepast (hoogte erbij)
- App aangepast (afhandelen als z-waarde ontbreekt)
