### ISSUE TITLE
GWSW HydX - Begin- en eindput van pompverbindingen incorrect

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#74]
Begin- en eindput van pompverbindingen komen niet overeen met de in de ttl opgegeven putten. In de ttl kloppen de pompverbindingen. In de hydx export lijkt het erop dat er 'één put te vroeg' als lozingsput wordt gebruikt in de hydx export.

**Comment by woutervriel** [comment]
Wouter stuurt voorbeeld .ttl Laren. Marco gaat details na van welk object het betreft

**Comment by MarinusVonhof** [comment]
Gecorrigeerd, het op de pomp aangesloten persleiding-tracé wordt nu (inclusief alle zijtakken) doorlopen totdat een inspectieput of lozingsput gevonden is.
In het voorbeeld Laren komt geen (op een pomp aangesloten) persleiding-tracé met zijtakken voor. Nog doortesten (met andere datasets?)
