### ISSUE TITLE
GWSW Hyd - Kolken wel in Hyd; niet in HydX

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#75]
Kolken worden niet meegenomen in knooppunt.csv, maar in de Hyd-nulmeting wordt er wel melding gemaakt van ontbrekende relaties (lengte, breedte en hoogte). Dat suggereert dat kolken wel naar HydX zouden moeten gaan. HydX levert een 1D strengenmodel. Kolken worden gebruikt in 2D simulaties waarbij interactie met de bovengrond aanwezig is. Meldingen in de Hyd-nulmeting verwijderen.

**Comment by woutervriel** [comment]
Kolken en aansluitleidingen moeten uit filter / cfk Hyd

**Comment by MarinusVonhof** [comment]
Kolk staat vanaf GWSW 1.6 niet meer in de CFK Hyd
