### ISSUE TITLE
GWSW HydX - Afsluitstukken incorrect in HydX

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#76]
Afsluitstukken worden incorrect naar HydX vertaald. Deze worden gemapt naar inspectieput. Echter de hydraulische werking van een afsluitstuk verandert daarmee volledig.

**Comment by woutervriel** [comment]
Duidelijk. Marinus zoekt het uit.

**Comment by MarinusVonhof** [comment]
Alle onbekende knooppunten die wel in het netwerk staan worden als Inspectieput geregistreerd (is zo afgestemd met de modelleurs). Dus allerlei hulpstukken worden een - geknevelde - inspectieput met minimale afmetingen.
De queries en de app daar nog wel op aanpassen.

**Comment by MarinusVonhof** [comment]
App aangepast
