### ISSUE TITLE
GWSW HydX - Maaiveldschematisering Blinde en verdekte putten

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#77]
Blinde en verdekte putten zouden geen maaiveldschematisering moeten kunnen hebben.

**Comment by woutervriel** [comment]
Deze hoort in het datamodel thuis eigenlijk (voorkeur). Of, automatische maaiveldschematisering toevoegen in queries.

**Comment by MarinusVonhof** [comment]
In app aangepast: bij blinde put wordt de maaiveldschematisering in HydX "gekneveld"
Voor verdekte put niet aangepast, die afdekking kan van alles zijn
