### ISSUE TITLE
GWSW HydX - Infiltratiebassin wordt Inspectieput

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#78]
In GWSW Hyd is ‘reservoir’ opgenomen. Echter, wanneer je een subtype van reservoir in een dataset naar HydX wilt converteren, wordt in de Knooppunt.csv vermeld dat Infiltratiebassin onbekend is en dat deze een inspectieput wordt. De infiltrerende werking komt daarmee compleet te vervallen. Het lijkt erop dat er nog een knooptype mist in HydX, namelijk een infiltratievoorziening.

**Comment by woutervriel** [comment]
Duidelijk. Marinus kijkt er naar. Hij hoort er sowieso in.

**Comment by MarinusVonhof** [comment]
Verwerkt in GWSW Apps, infiltratiebassin wordt nu behandeld als infiltratieput (knooppunttype "ITP")
