### ISSUE TITLE
GWSW HydX - Wanddikte-bepaling

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#79]
Hydx levert binnenmaten terug van leidingafmetingen. Zie als voorbeeld streng 150601-150702 (HPE). Afmetingen 600 mm bij 640 mm. Maar in hydx verbindingen csv komt deze terug als profiel met afmetingen 571 mm bij 611 mm. Hoe bepaalt hydx de wanddikte? En bij streng 2671I-2673I met diameter 630 mm wordt het 599 mm (PVC).

**Comment by woutervriel** [comment]
In datasets moet je wel de juiste diameter invullen (bij plastic dus de buitendiameter)

**Comment by MarinusVonhof** [comment]
Het profiel van kunsstof leidingen wordt als volgt bepaald:
                  /**
                   * Bepaal het profiel bij kunststof-leidingen:
                   * 
                   * Leiding is van kunststof als de HydX-materiaalcode is PVC of HPE
                   * Bij kunsstof-leidingen is de doorsnede-afmeting (breedte, hoogte, diameter) altijd buitenwerks
                   * De binnenmaat (het profiel) wordt voor alle leidingvormen als volgt bepaald:
                   * 
                   * - het kenmerk Wanddikte is ingevuld: 
                   *   de binnenmaat wordt [breedte/hoogte - 2*wanddikte]
                   * 
                   * - geen Wanddikte, wel kenmerk SDR_waarde ingevuld
                   *   de wanddikte wordt [breedte / sdr], de binnenmaat wordt [breedte/hoogte - 2*wanddikte]
                   * 
                   * - geen Wanddikte en geen SDR_waarde ingevuld
                   *   er wordt uitgegaan van SDR_waarde 41, zie verder hiervoor
                   */
