### ISSUE TITLE
In excellijst met GWSW-datasets de PDOK deelname opnemen

### ISSUE THREAD

**Issue by MarinusVonhof** [StichtingRIONED/GWSW_Apps#81]
In de csv-download een extra kolom toevoegen met daarin de PDOK-marker

**Comment by Markambi** [comment]
Super! 
En het is belanbgrijk dat indien er in een lijst staat dat de gemeente op PDOK wordt ontsloten ook daadwerkelijk de rioleringsdata wordt ontsloten. En iid bevraagbaar met API (zoals #82)

**Comment by MarinusVonhof** [comment]
De PDOK-kolom is toegevoegd aan de csv
