### ISSUE TITLE
Hydx query 'Hyd_Knooppunt.rq'

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#83]
De twee regels 37 en 38 in Hyd_Knooppunt.rq zorgen ervoor dat BlindePut en VerdektePut eruit worden gefilterd. De netwerkopbouw tussen putten en leidingen wordt daarmee verbroken. De betreffende putten komen niet terecht in knooppunt.csv. Bij verbinding.csv wordt dan 'onbekend' vermeld als begin- of eindpunt van de leiding.

Enkel de maaivedschematisering mag niet Reservoir worden, maar gekneveld.

**Comment by MarinusVonhof** [comment]
Zie ook ander issue: geen actie nodig. In de dataset ook het functionele type toevoegen.
