### ISSUE TITLE
GWSW download ontologie Error

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#92]
Op de hoofdpagina van https://data.gwsw.nl/ zijn via een viertal knoppen onderdelen van het GWSW te downloaden: concepten, soorten, samenstelling en bron .ttl. 

De knoppen geven enkel 'download.html' terug ipv de gewenste output.

**Comment by MarinusVonhof** [comment]
Bedankt voor de tip Wouter, is ondertussen verholpen.
