### ISSUE TITLE
HydX: DIT riool wordt leidingtype GSL

### ISSUE THREAD

**Issue by woutervriel** [StichtingRIONED/GWSW_Apps#99]
DIT-riool wordt vertaald naar gesloten leiding (GSL). Waarom niet naar IT?

Ook de velden bij Itobject.csv moeten worden gevuld wanneer de leiding als ITR bij VRB_TYP zou moeten komen te staan.

**Comment by MarinusVonhof** [comment]
Bedankt voor tip, aangepast. 
De URI DIT_Riool wordt nu als infiltrerend beschouwd.
